import pic1 from "../../assets/images/pic-1.png";
import pic2 from "../../assets/images/pic-2.png";
import pic3 from "../../assets/images/pic-3.png";
import pic4 from "../../assets/images/pic-4.png";
import pic5 from "../../assets/images/pic-5.png";
import pic6 from "../../assets/images/pic-6.png";
import pic7 from "../../assets/images/pic-7.png";
import pic8 from "../../assets/images/pic-8.png";

export const TicketName = [
  {
    id: 1,
    img: pic1,
    text: "Contact Email not Linked",
    lowerText: "Updated 1 day ago",
    customerName: "Tom Cruise",
    customerDate: "on 24.05.2019",
    date: "May 26, 2019",
    datetime: "6:30 PM",
    priority: "HIGH",
    priorityClassHigh: "high",
  },
  {
    id: 2,
    img: pic2,
    text: "Adding Images to Featured Posts",
    lowerText: "Updated 1 day ago",
    customerName: "Matt Damon",
    customerDate: "on 24.05.2019",
    date: "May 26, 2019",
    datetime: "8:00 AM",
    priority: "LOW",
    priorityClassLow: "low",
  },
  {
    id: 3,
    img: pic3,
    text: "When will I be charged this month?",
    lowerText: "Updated 1 day ago",
    customerName: "Robert Downey",
    customerDate: "on 24.05.2019",
    date: "May 26, 2019",
    datetime: "7:30 PM",
    priority: "HIGH",
    priorityClassHigh: "high",
  },
  {
    id: 4,
    img: pic4,
    text: "Payment not going through",
    lowerText: "Updated 2 day ago",
    customerName: "Christian Bale",
    customerDate: "on 24.05.2019",
    date: "May 25, 2019",
    datetime: "5:00 PM",
    priority: "NORMAL",
    priorityClassNormal: "normal",
  },
  {
    id: 5,
    img: pic5,
    text: "Unable to add replies",
    lowerText: "Updated 2 day ago",
    customerName: "Henry Cavil",
    customerDate: "on 24.05.2019",
    date: "May 25, 2019",
    datetime: "4:00 PM",
    priority: "HIGH",
    priorityClassHigh: "high",
  },
  {
    id: 6,
    img: pic6,
    text: "Downtime since last week",
    lowerText: "Updated 3 day ago",
    customerName: "Chris Evans",
    customerDate: "on 23.05.2019",
    date: "May 25, 2019",
    datetime: "2:00 PM",
    priority: "NORMAL",
    priorityClassNormal: "normal",
  },
  {
    id: 7,
    img: pic7,
    text: "Referral Bonus",
    lowerText: "Updated 4 day ago",
    customerName: "Sam Smith",
    customerDate: "on 22.05.2019",
    date: "May 25, 2019",
    datetime: "11:30 AM",
    priority: "LOW",
    priorityClassLow: "low",
  },
  {
    id: 8,
    img: pic8,
    text: "How do I change my password?",
    lowerText: "Updated 6 day ago",
    customerName: "Steve Rogers",
    customerDate: "on 21.05.2019",
    date: "May 24, 2019",
    datetime: "1:00 PM",
    priority: "NORMAL",
    priorityClassNormal: "normal",
  },
];
